// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/shorten":{"post":{"description":"Create a short URL for a given long URL","consumes":["application/json"],"produces":["application/json"],"tags":["urls"],"summary":"Shorten a URL","parameters":[{"description":"URL to shorten","name":"url","in":"body","required":true,"schema":{"$ref":"#/definitions/handlers.ShortenRequest"}}],"responses":{"201":{"description":"Created","schema":{"type":"object","additionalProperties":{"type":"string"}}},"400":{"description":"Bad Request","schema":{"type":"object","additionalProperties":{"type":"string"}}}}}}},"definitions":{"handlers.ShortenRequest":{"type":"object","required":["url"],"properties":{"url":{"type":"string"}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "URL Shortener API",
	Description:      "A high-performance URL shortening service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
